# Release a new version in Git
name: Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # Mandatory type of release to create
      releaseType:
        description: 'Type of release (major, minor, patch)'
        required: true
        default: 'minor'
jobs:
  release:
    name: release new version
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # create a new release of the given type
      - name: create release
        run: git config --global user.name 'peveuve'
        run: git config --global user.email 'peveuve@users.noreply.github.com'
        run: npm version ${{github.event.inputs.releaseType}}
      # push the commit and tag
      - name: push release
        run: git push && git push --tags
